name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
    paths:
      - "server/**"
      - "client/**"
  pull_request:
    branches: [ main ]
    paths:
      - "server/**"
      - "client/**"

jobs:
  # Build & test on Pull Request
  build-images-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [server, client]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('${{ matrix.service }}/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          load: true
          tags: wcygan/grpc-chat-${{ matrix.service }}:pr
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Build & Push on push to main
  build-and-push-images:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [server, client]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('${{ matrix.service }}/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Determine version
        id: version
        run: echo "VERSION=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV

      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=registry,ref=wcygan/grpc-chat-${{ matrix.service }}:latest
          cache-to: type=inline
          tags: |
            wcygan/grpc-chat-${{ matrix.service }}:latest
            wcygan/grpc-chat-${{ matrix.service }}:${{ env.VERSION }} 